// Single source of truth for which lucide-react icons are actually used in this project,
// and where. Keep this in sync when a component starts or stops using an icon — the
// Foundations → Icons gallery reads it to badge icons as "in use".
export const USED_ICONS: Record<string, string[]> = {
  ChevronDown: ['Breadcrumb', 'ButtonGroup', 'Select', 'Table', 'Combobox', 'FilterDropdown', 'FilterChip'],
  ChevronLeft: ['Breadcrumb', 'Table', 'Calendar'],
  ChevronRight: ['Table', 'Calendar'],
  ChevronsLeft: ['Table'],
  ChevronsRight: ['Table'],
  MoreHorizontal: ['Breadcrumb', 'Table'],
  Loader2: ['Button', 'BaseInput', 'Combobox'],
  Plus: ['Button'],
  ArrowRight: ['Button'],
  ArrowUp: ['Table'],
  ArrowDown: ['Table'],
  ArrowUpDown: ['Table'],
  Search: ['Button', 'Combobox', 'FilterDropdown', 'ColumnCustomizer'],
  SearchX: ['Combobox', 'FilterDropdown', 'ColumnCustomizer'],
  Bold: ['ButtonGroup'],
  Italic: ['ButtonGroup'],
  Underline: ['ButtonGroup'],
  Mail: ['TextInput'],
  X: ['BaseInput', 'Select', 'Combobox', 'FilterDropdown', 'ColumnCustomizer', 'FilterChip', 'DatePicker'],
  CreditCard: ['TextInput'],
  CircleAlert: ['BaseInput', 'Select', 'OTPInput'],
  CircleCheck: ['BaseInput', 'Select', 'OTPInput', 'Combobox'],
  TriangleAlert: ['Badge'],
  Info: ['BaseInput', 'Select', 'Table'],
  Filter: ['Table'],
  Calendar: ['DatePicker'],
  MoreVertical: ['Table'],
  Pencil: ['Table'],
  Cloud: ['Table'],
  RefreshCw: ['Table'],
  CloudOff: ['Table'],
  CloudAlert: ['Table'],
  Check: ['Table', 'Checkbox', 'ColumnCustomizer'],
  Minus: ['Table', 'Checkbox'],
  WrapText: ['Table'],
  AlignLeft: ['Table'],
  Trash2: ['Table'],
  Columns3: ['ColumnCustomizer'],
  GripVertical: ['ColumnCustomizer'],
  Lock: ['ColumnCustomizer'],
  Pin: ['ColumnCustomizer'],
  PinOff: ['ColumnCustomizer'],
  Undo2: ['ColumnCustomizer'],
}
