// Single source of truth for which lucide-react icons are actually used in this project,
// and where. Keep this in sync when a component starts or stops using an icon — the
// Foundations → Icons gallery reads it to badge icons as "in use".
export const USED_ICONS: Record<string, string[]> = {
  ChevronDown: ['Breadcrumb', 'ButtonGroup', 'Select', 'Table', 'Combobox', 'FilterDropdown', 'FilterChip', 'DatePicker', 'TopNav', 'SideNav'],
  ChevronLeft: ['Breadcrumb', 'Table', 'Calendar', 'DatePicker', 'BulkActionBar', 'Drawer'],
  ChevronRight: ['Table', 'Calendar', 'DatePicker', 'BulkActionBar', 'SideNav', 'Drawer'],
  ChevronsLeft: ['Table'],
  ChevronsRight: ['Table'],
  MoreHorizontal: ['Breadcrumb', 'Table'],
  Loader2: ['Button', 'BaseInput', 'Combobox', 'Filters'],
  Plus: ['Button', 'Drawer'],
  ArrowRight: ['Button'],
  ArrowUp: ['Table'],
  ArrowDown: ['Table'],
  ArrowUpDown: ['Table'],
  Search: ['Button', 'Combobox', 'FilterDropdown', 'ColumnCustomizer', 'Filters'],
  SearchX: ['Combobox', 'FilterDropdown', 'ColumnCustomizer', 'Filters'],
  Bold: ['ButtonGroup'],
  Italic: ['ButtonGroup'],
  Underline: ['ButtonGroup'],
  Mail: ['TextInput'],
  X: ['BaseInput', 'Select', 'Combobox', 'FilterDropdown', 'ColumnCustomizer', 'FilterChip', 'DatePicker', 'Filters', 'BulkActionBar', 'Drawer'],
  CreditCard: ['TextInput'],
  CircleAlert: ['OTPInput', 'Filters'],
  CircleCheck: ['OTPInput', 'Combobox'],
  TriangleAlert: ['Badge'],
  Info: ['BaseInput', 'Select', 'Table'],
  Filter: ['Table'],
  Calendar: ['DatePicker', 'DateFilter'],
  MoreVertical: ['Table'],
  Pencil: ['Table'],
  Cloud: ['Table'],
  RefreshCw: ['Table'],
  CloudOff: ['Table'],
  CloudAlert: ['Table'],
  Check: ['Table', 'Checkbox', 'ColumnCustomizer'],
  Minus: ['Table', 'Checkbox'],
  WrapText: ['Table'],
  AlignLeft: ['Table'],
  Trash2: ['Table', 'BulkActionBar'],
  Columns3: ['ColumnCustomizer'],
  GripVertical: ['ColumnCustomizer'],
  Lock: ['ColumnCustomizer'],
  Pin: ['ColumnCustomizer'],
  PinOff: ['ColumnCustomizer'],
  Undo2: ['ColumnCustomizer'],
  ListFilter: ['Filters'],
  CheckCheck: ['BulkActionBar'],
  PanelLeftClose: ['SideNav'],
  PanelLeftOpen: ['SideNav'],
  // Generic placeholders in the TopNav and SideNav stories.
  LayoutGrid: ['SideNav'],
  Inbox: ['SideNav'],
  Folder: ['SideNav', 'Drawer'],
  CalendarDays: ['SideNav'],
  BookOpen: ['SideNav'],
  ChartColumn: ['SideNav'],
  Settings: ['SideNav', 'TopNav'],
  Hexagon: ['TopNav'],
  CircleHelp: ['TopNav'],
  Bell: ['TopNav'],
  User: ['TopNav'],
  LogOut: ['TopNav'],
  // Generic placeholders in the Drawer stories.
  CirclePlay: ['Drawer'],
  Paperclip: ['Drawer'],
  Save: ['Drawer'],
  SlidersHorizontal: ['Drawer'],
}
